/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Vincent Yanez (https://sketchfab.com/vinceyanez)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/minecraft-iron-golem-b7f1a9a021654c84a67a1ead67291793
title: Minecraft - Iron Golem
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

import { getModelPath } from 'utils/getModelPath'

export function Golem(props) {
  const { nodes, materials } = useGLTF(getModelPath('Golem'))
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group rotation={[-Math.PI / 2, 0, 0]}>
            <group position={[0, 1.5, -0.75]}>
              <mesh geometry={nodes.Iron_Golem_Iron_Golem_0.geometry} material={materials.Iron_Golem} />
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')
